version: '3'

services:
  proxy:
    build: .
    image: aesuan/seeel-proxy
    ports:
      - 80:3000
    command: npm start
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always